from typing import Mapping

from ..streams import IPathVideoInStreamFactory, IPathVideoOutStreamFactory

DEFAULT_PATH_IN_STREAM_FACTORY: str
DEFAULT_PATH_OUT_STREAM_FACTORY: str

DEFAULT_PATH_IN_STREAM_PATH: str
DEFAULT_PATH_OUT_STREAM_PATH: str

PATH_IN_STREAM_FACTORIES: Mapping[str, IPathVideoInStreamFactory]
PATH_OUT_STREAM_FACTORIES: Mapping[str, IPathVideoOutStreamFactory]

DEFAULT_PATH_IN_STREAM_FACTORY = "picamera"
DEFAULT_PATH_OUT_STREAM_FACTORY = "ffmpeg_h264"

DEFAULT_PATH_IN_STREAM_PATH = "-"
DEFAULT_PATH_OUT_STREAM_PATH = "-"
