from ..keras_models.classification import KERAS_CLASSIFICATION_MODEL_FACTORY

MODEL_FACTORIES = [
    KERAS_CLASSIFICATION_MODEL_FACTORY
]

DEFAULT_MODEL_FACTORY = KERAS_CLASSIFICATION_MODEL_FACTORY.name